export const SUBMIT_DEVICE_ID_ENDPOINT = '/devices'
export const SUBMIT_DEVICE_NOTIFICATION_TOKEN = '/wallets/register-notification-devices'
export const GET_SESSION_BY_WALLET = '/sessions/wallet'
export const SUBMIT_WALLET_ENDPOINT = '/wallets'
export const SUBMIT_WALLET_NICKNAME_ENDPOINT = '/wallets/nickname'
export const GET_WALLET_NICKNAME_ENDPOINT = '/wallets/'
export const FIND_WALLET_BY_NICKNAME = '/wallets/find-by-nickname/'
export const SUBMIT_CLAIM_REQUEST_ENDPOINT = '/membership-requests'
export const SUBMIT_CLAIM_JUPITER_REQUEST_ENDPOINT = '/jupiter-membership-requests'
export const FETCH_CLAIM_REQUEST_ENDPOINT = '/membership-requests/request-from-device-or-wallet'

export const ALL_NOTI_ENDPOINT = '/notifications/own-noti'
export const MARK_ALL_NOTI_READ_ENDPOINT = '/notifications/read-all'
export const MARK_SINGLE_NOTI_READ = '/notifications/read'