export const SUBMIT_DEVICE_ID_ENDPOINT = '/devices'
export const SUBMIT_DEVICE_NOTIFICATION_TOKEN = '/wallets/register-notification-devices'
export const SUBMIT_WALLET_ENDPOINT = '/wallets'
export const SUBMIT_WALLET_NICKNAME_ENDPOINT = '/wallets/nickname'
export const GET_WALLET_NICKNAME_ENDPOINT = '/wallets/nickname'
export const SUBMIT_CLAIM_REQUEST_ENDPOINT = '/membership-requests'
export const SUBMIT_CLAIM_JUPITER_REQUEST_ENDPOINT = '/jupiter-membership-requests'
export const FETCH_CLAIM_REQUEST_ENDPOINT = '/membership-requests/request-from-device-or-wallet'